version: "3.4"


services:
  poste:
    image: analogic/poste.io
    restart: always
    network_mode: "host"
    ports:
      - "3001:80"
    expose:
      - 25
      - 443
      - 110
      - 143
      - 465
      - 587
      - 993
      - 995
    volumes:
      - /root/mail-data/:/data
    environment:
      - HTTPS=ON
